# Generated by Django 5.0 on 2023-12-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tank', 'Танк'), ('Healing', 'Хилы'), ('Dd', 'ДД'), ('Trader', 'Продавцы'), ('Gildmaster', 'Гилдмастеры'), ('Questgiver', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('Potion_Makers', 'Зельевары'), ('Spell_Masters', 'Мастера Заклинаний')], default='Tank', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
